version: "3.3"
services:
  zalo-server:
    image: tienta/zalo-server:latest
    ports:
      - "${CONTAINER_PORT:-3080}:${CONTAINER_PORT:-3080}" # Ánh xạ cổng động cho Express
      - "${CONTAINER_PORT_WS:-3001}:${CONTAINER_PORT_WS:-3001}" # Ánh xạ cổng động cho WebSocket
    volumes:
      - type: bind
        source: ./zalo_data
        target: /app/cookies
        consistency: consistent
      - type: bind
        source: ./zalo_data/proxies.json
        target: /app/proxies.json
        consistency: consistent
      - type: bind
        source: ./zalo_data/webhook-config.json
        target: /app/webhook-config.json
        consistency: consistent
    environment:
      - CONTAINER_IP=0.0.0.0
      - CONTAINER_PORT=3080
      - CONTAINER_PORT_WS=3001 # Biến môi trường cho WebSocket
      - MESSAGE_WEBHOOK_URL=${MESSAGE_WEBHOOK_URL:-/app/webhook-config.json}
      - GROUP_EVENT_WEBHOOK_URL=${GROUP_EVENT_WEBHOOK_URL:-/app/webhook-config.json}
      - REACTION_WEBHOOK_URL=${REACTION_WEBHOOK_URL:-/app/webhook-config.json}
    restart: always
    working_dir: /app
