version: "3.3"
services:
  zalo-server:
    image: tienta/zalo-server:latest
    ports:
      - "${CONTAINER_PORT:-3000}:${CONTAINER_PORT:-3000}" # Ánh xạ cổng động cho Express
    volumes:
      - type: bind
        source: ./zalo_data
        target: /app/cookies
        consistency: consistent
      - type: bind
        source: ./zalo_data/proxies.json
        target: /app/proxies.json
        consistency: consistent
      - type: bind
        source: ./zalo_data/webhook-config.json
        target: /app/webhook-config.json
        consistency: consistent
    environment:
      - CONTAINER_IP=0.0.0.0
      - CONTAINER_PORT=3000
      - MESSAGE_WEBHOOK_URL=${MESSAGE_WEBHOOK_URL:-/app/webhook-config.json}
      - GROUP_EVENT_WEBHOOK_URL=${GROUP_EVENT_WEBHOOK_URL:-/app/webhook-config.json}
      - REACTION_WEBHOOK_URL=${REACTION_WEBHOOK_URL:-/app/webhook-config.json}
    restart: always
    working_dir: /app
